version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik29
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web-secure.address=:443
      - --providers.file.directory=/configuration
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/configuration
      - ./certs:/certs

  mysql:
    image: mysql:5.7.32
    container_name: mysql57
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: supersecret

  redis:
    image: redis:7.0.8-alpine
    container_name: redis708
    restart: unless-stopped
    ports:
      - 6379:6379

  mailhog:
    image: corpusops/mailhog:v1.0.1
    container_name: mailhog101
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch861
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  # project_<projectname>:
  #   build:
  #     context: .
  #     dockerfile: workcontainer.dockerfile
  #     args:
  #       NODE_VERSION: 18.6.0
  #       PHP_VERSION: 8.2.1
  #   container_name: project_<projectname>
  #   ports:
  #     - "8081:8080" # use different port for each project ... 8081:8080, 8082:8080, 8083:8080 ...
  #   volumes:
  #     - ~/www/<project_folder>:/var/www/html
  #     - ./.ashrc:/etc/.ashrc
  #   labels:
  #     - "traefik.http.routers.project_<projectname>.rule=Host(`<project_domain>.test`)"
  #     - "traefik.http.routers.project_<projectname>.tls=true"
  #   depends_on: # update this list with the services required by the project
  #     - traefik
  #     - mysql
