version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik29
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web-secure.address=:443
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configuration:/configuration
      - ./certs:/certs

  mysql:
    image: mysql:5.7.32
    container_name: mysql57
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: supersecret

  redis:
    image: redis:7.0.8-alpine
    container_name: redis708
    restart: unless-stopped
    ports:
      - 6379:6379
  
  mailhog:
    image: corpusops/mailhog:v1.0.1
    container_name: mailhog101
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

  # project_<projectname>:
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: <projectname>.dockerfile
  #   container_name: project_<projectname>
  #   ports:
  #     - "8081:8081" # use different ports for each project
  #   volumes:
  #     - ~/www/<project_folder>:/var/www/html
  #   labels:
  #     - "traefik.http.routers.project_<projectname>.rule=Host(`<project_domain>.test`)"
  #     - "traefik.http.routers.project_<projectname>.tls=true"
  #   depends_on:
  #     - traefik
  #     - mysql57
